### ISSUE TITLE
Have you grabbed the Revived Witch packets and saved them? 

### ISSUE THREAD

**Issue by MHfudie** [dormant-witch/nekofs#1]
i want try dormant witch to Revived Witch

**Comment by yxnan** [comment]
I got all the files archived before server shutdown, if this can help please contact me

![Schermafdruk van 2024-02-18 03-12-14](https://github.com/dormant-witch/nekofs/assets/16621623/bec7e6c8-c1ef-47fa-ae4a-0ce19a4bbca3)
